### ISSUE TITLE
[BUG]  Error E575 - Illegal starting character in line

### ISSUE THREAD

**Issue by aw040147** [SCOREC/fep#15]
**Describe the bug**
@cwsmith I started experiencing an error code E575 - Illegal starting character in line: ^I^I1^I0 while opening and/or closing the vim editor since yesterday evening. Prior to it, everything was running smoothly. I initially thought it was some issues with the a2.cc file. I then re-copied the contents of the barn-shared folder to get a fresh file but now I can't even run the one time setup ./setup.sh or the compiler ./build.sh after editing the a2.cc file. One other error message that keeps on popping up is "disk quota exceeded".

**To Reproduce**
Either run vi a2.cc or run the ./setup.sh.

**Expected behavior**
I have added the screenshot of the error message and the error log file generated while running setup.

**Screenshots**
![1](https://user-images.githubusercontent.com/80629644/111069992-06e46100-84a6-11eb-82da-1cfb5d8ae366.jpg)

**Additional context**
[CMakeError.log](https://github.com/SCOREC/fep/files/6136715/CMakeError.log)

**Comment by cwsmith** [comment]
@aw040147 Thank you.  I think is related to #14.  As of this last night/this morning the FEP5 home directory quota had been reached (i.e, out of disk space for the project).  Since then, files have been deleted/moved, and there should be plenty of free space.  

Please try editing the assignment files with `vim` again in your home directory.

**Comment by aw040147** [comment]
@cwsmith Thank you for your support. Everything is working fine now.
