### ISSUE TITLE
a4: Constitutive equation for advection-diffusion [Question]

### ISSUE THREAD

**Issue by anilkamat** [SCOREC/fep#28]
## Summary
I am not quite sure how to calculate the constitutive matrix [D] in the element stiffness matrix for advection-diffusion. @mortezah It would be great if you could point me some resources to do that. Thanks.

**Comment by mortezah** [comment]
@anilkamat I am assuming your question is in regards to task 2. For the advective term there would be no constitutive matrix. All you need to know is the advection constant `a` which in this case you will assume is the vector `[1, 1]`.

**Comment by goinea** [comment]
So a=D in this case or is the form for our stiffness matrix not include D for this step?

**Comment by mortezah** [comment]
@anilkamat you need to re-write the weak form corresponding to the advective term, in in the finite element space, then it become clear what are the different components of the element matrix.

See for example this page
https://en.m.wikipedia.org/wiki/Stiffness_matrix

Note that since the advective term has the from w ai u,i you will end up having shape function times shape function derivative (as opposed to the diffusive term where you have shape function derivative times shape function derivative)

**Comment by anilkamat** [comment]
It was helpful.  Thank you!!
