### ISSUE TITLE
W for element stiffness 

### ISSUE THREAD

**Issue by startrekman** [SCOREC/fep#29]
So since we are on [0,1] instead of [-1,1], when we performed quad integration, do we need to change the integration points using the formula listed on this page for an integral from a to b? If sure, I am unsure how to change the ip locations. 

https://en.wikipedia.org/wiki/Gaussian_quadrature

Any advice/ pointers would be very helpful, thank you for your help.

**Comment by mortezah** [comment]
@startrekman 

Can you be a little more specific as to what part of the assignment this question is in regards to?

The interval information is taken care of by doing a change of coordinate. Say you want to integrate `f(x)` over a given element `Int f(x) dx`. First, you need to re-write that integral in the parametric (xi) coordinate (note that that would introduce a Jacobian determinant) so you will have something like `Int f(xi) det(J) dxi`. Then you will apply the quadrature to the integral in terms of `xi`. That way, you do not have to worry about change of coordinates since MFEM (and most finite element code) will give you the quadrature points and weights in the parent (xi) coordinates.

**Comment by startrekman** [comment]
Are you refrencing ip.weight?

**Comment by mortezah** [comment]
![formula](https://render.githubusercontent.com/render/math?math=e^{i \pi} = -1)

**Comment by mortezah** [comment]
@startrekman  I am not sure if I understand your comment.

In general to compute the integral 

<img src="https://render.githubusercontent.com/render/math?math=\int f(\xi) d\xi">

using quadrature you will use the sum

<img src="https://render.githubusercontent.com/render/math?math=\sum_{q}f(\xi_q) w_q">

where <img src="https://render.githubusercontent.com/render/math?math=\xi_q"> is the coordinate of the `q`th quadrature point and <img src="https://render.githubusercontent.com/render/math?math=w_q"> is the weight associated with it.

In applications  you usually need to compute the following integral (over the physical space)

<img src="https://render.githubusercontent.com/render/math?math=\int_{\Omega_e} f(x) dx">

to do this will first need to transform the integral into the parent coordinate of the element using change of variable (see for example https://www.math24.net/change-variables-triple-integrals) to get 

 <img src="https://render.githubusercontent.com/render/math?math=\int f(\xi) J(\xi) d\xi">

where `J` is the determinant of the Jacobian. Then you will apply the quadrature rule.
