### ISSUE TITLE
Can't Access Any CCI Landing Pads

### ISSUE THREAD

**Issue by BryanMcKeever** [SCOREC/fep#36]
I apologize that this is tangentially related to FEP and the assignments, but I currently cannot access any of the CCI landing pads using ssh FEP6mckv@blp01.ccni.rpi.edu, my PIN+Token, and Password as I have always done. 

Is anyone else having this issue currently?

I did put in an ITSSC request ticket, but are there folks who can help outside of business hours?

**Comment by cwsmith** [comment]
@BryanMcKeever Did you hear back from CCI support?  Is it working now?  I heard from a few other folks last night that had problems logging in.

**Comment by startrekman** [comment]
I can ssh into the supercomputer, I'm trying to set up a Jupiter 
notebook / gui by following the steps here:

https://docs.cci.rpi.edu/software/Jupyter_notebook/


I am having problems with doing "Connect a new SSH session from your 
client with a port forward to the allocated node"
due to not knowing what to input for username and pasword. There are not 
3 input options (pin+pic, username, pascode)
so I am not sure what to do. I am attempting to use remmina on linux. Is 
there is a better software/ ssh portal you
support for linux users?

Very Respectfully,
AJ

**Comment by cwsmith** [comment]
@startrekman Thanks for confirming you can connect.

Please create a new issue for the ssh tunnel/port forward question.

**Comment by BryanMcKeever** [comment]
@cwsmith, yes. It was working once again last night.

**Comment by cwsmith** [comment]
Thank you. I'll close this issue.
